const leadersData = [
    {
        id: 1,
        name: "Prophet Muhammad (PBUH)",
        short_name: "muhammad",
        father_name: "Abdullah",
        army_led: "Muslim community in Medina",
        date_of_death: "632 AD",
        battles_won: "23 (Battles are not the primary focus of his leadership)",
        battles_lost: 0,
    },
    {
        id: 2,
        name: "Abu Bakr (R.A.)",
        short_name: "bakr",
        father_name: "Abu Quhafah",
        army_led: "Muslim armies during the Ridda Wars",
        date_of_death: "634 AD",
        battles_won:
            "Multiple victories against rebellious tribes, Specific numbers may vary",
        battles_lost: "Unknown",
    },
    {
        id: 3,
        name: "Umar ibn Khattab (R.A.)",
        short_name: "umar",
        father_name: "Khattab ibn Nufil",
        army_led: "Muslim armies during territorial expansion",
        date_of_death: "644 AD",
        battles_won:
            "Significant conquests, including Jerusalem, Specific numbers may vary",
        battles_lost: 2,
    },
    {
        id: 4,
        name: "Uthman ibn Affan (R.A.)",
        short_name: "uthman",
        father_name: "Affan ibn Abi Al-Haas",
        army_led: "Continuation of Muslim conquests",
        date_of_death: "656 AD",
        battles_won:
            "Expansion of Islamic territory, Specific numbers may vary",
        battles_lost: "Unknown",
    },
    {
        id: 5,
        name: "Ali ibn Abi Talib (R.A.)",
        short_name: "ali",
        father_name: "Abu Talib",
        army_led: "Muslim armies in internal conflicts",
        date_of_death: "661 AD",
        battles_won:
            "Victories in battles like Battle of the Camel, Specific numbers may vary",
        battles_lost: 3,
    },
    {
        id: 6,
        name: "Khalid ibn al-Walid",
        short_name: "khalid",
        father_name: "Waleed ibn Mughira",
        army_led: "Muslim army during the Rashidun Caliphate",
        date_of_death: "642 AD",
        battles_won: 43,
        battles_lost: 0,
    },
    {
        id: 7,
        name: "Salahuddin Ayyubi",
        short_name: "salahuddin",
        father_name: "Ayyub",
        army_led: "Ayyubid Dynasty",
        date_of_death: "1193 AD",
        battles_won: 27,
        battles_lost: 4,
    },
    {
        id: 8,
        name: "Muhammad ibn Qasim",
        short_name: "qasim",
        father_name: "Qasim ibn Muhammad ibn Abi Waqas",
        army_led: "Umayyad Caliphate",
        date_of_death: "715 AD",
        battles_won: 8,
        battles_lost: 0,
    },
    {
        id: 9,
        name: "Ibrahim Pasha",
        short_name: "ibrahim",
        father_name: "Mehmed Pasha",
        army_led: "Ottoman Empire",
        date_of_death: 1683,
        battles_won: 20,
        battles_lost: 8,
    },
    {
        id: 10,
        name: "Sultan Mehmed II",
        short_name: "mehmed",
        father_name: "Murad II",
        army_led: "Ottoman Empire",
        date_of_death: "1481 AD",
        battles_won: 23,
        battles_lost: 2,
    },
];

export default leadersData;
